GRBR-463: Creation of a new Validation in SignaturePolicy validation …
davydsantos/dss pull request #9
Opened 2017-11-17 17:50 UTC by fernandoraffani

…chain, that makes the Formal Policy Validation if it is implemented by the Custom Validation (when the Policy is in ASN1 format and signature can be validated against it).

The implementation was made so that the Formal Validation is configurable in the xml and optional, with the default value being to skip validation, so it doesn't affect all the other policy that cannot have specific elements validated against the signature.

2017-11-17 23:41 UTC, davydsantos requested changes
Some changes seem to be unrelated to this PR...

2017-11-17 23:41 UTC, davydsantos commented on validation-policy/src/main/java/eu/europa/esig/dss/validation/policy/EtsiValidationPolicy.java
> +			CryptographicConstraint sigCryptographic = basicSignature.getCryptographic();
Is this related to the SignaturePolicyChain?

2017-11-17 23:41 UTC, davydsantos commented on validation-policy/src/main/java/eu/europa/esig/dss/validation/policy/EtsiValidationPolicy.java
> +			CryptographicConstraint certCryptographic = certificateConstraints.getCryptographic();
Is this related to the SignaturePolicyChain?

2017-11-21 11:28 UTC, fernandoraffani commented
@davydsantos: I have removed the changes you have noted. 

They were due to differences between master and the version linked to validation-authority that probably need to be merged at some point. However, as they were not part of this fix, I removed them from this PR.

2017-11-22 12:36 UTC, pauloverzini approved these changes

2017-11-22 18:06 UTC, fernandoraffani commented
Deprecated: created a new PR: https://github.com/davydsantos/dss/pull/10, that consists of the same changes, but in a branch created from signature-policy branch.

https://jira.corp.docusign.com/browse/GRBR-463
includes https://jira.corp.docusign.com/browse/GRBR-367

2017-11-22 18:06 UTC, closed without merging